[SQUASH]sdm845-common: Add unified bdroid header Signed-off-by: optimus9811 <Optimus9811@github.com>
sdm845-common: bluetooth: Switch to a map based BT name

Change-Id: I6e0457441c5d2e7fd936d117439a90ae84496dc2
Signed-off-by: chandu078 <chandudyavanapelli03@gmail.com>

sdm845-common: bluetooth: Fix undefined PROPERTY_VALUE_MAX

 * vendor/qcom/opensource/commonsys/bluetooth_ext/system_bt_ext/bta/swb/bta_ag_swb.cc:142:14: error: use of undeclared identifier 'PROPERTY_VALUE_MAX'
   char value[PROPERTY_VALUE_MAX];

Change-Id: Iaa9458296d71feacc88f5f04d7f5b99616115f23
Signed-off-by: chandu078 <chandudyavanapelli03@gmail.com>

Co-authored-by: LuK1337 <priv.luk@gmail.com>
Co-authored-by: dianlujitao <dianlujitao@lineageos.org>
Signed-off-by: chandu078 <chandudyavanapelli03@gmail.com>